- 
  name: copy file to destination server
  hosts: all
  tasks:
   - copy:
      src: /home/abhilash/text.txt
      dest: /root/test.txt
      owner: root
      group: root
      mode: 0644
- 
  name: copy file2 to destination server
  hosts: all
  tasks:
   - copy:
      content: | 
        Cecilia Chapman
        711-2880 Nulla St.
        Mankato Mississippi 96522
        (257) 563-7401
      dest: /root/address.txt
      owner: root
      group: root
      mode: 0644

