- 
  name: install Nginx
  hosts: all
  tasks:
    - name: install nignx on debian
      apt:
        name: nignx
        state: installed
      when: ansible_os_family == "Debian" and
            ansible_distribution_version == "16.04"
    - name: install nginx on redhat systems
      yum:
        name:  nignx
        state: installed
      when: ansible_os_family == "Redhat" or
            ansible_os_family == "Suse"

      
